services:
  postgres:
    image: postgres:15
    container_name: deposit_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${PG_USER} -d $${PG_DATABASE} -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: deposit_api
    ports:
      - "3779:3779"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head &&
             uvicorn run_app:app --host 0.0.0.0 --port 3779"

volumes:
  postgres_data:
