"""initial migration

Revision ID: e8a0660684a6
Revises: 
Create Date: 2024-12-19 12:59:28.098366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a0660684a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('calculation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('date', 'periods', 'amount', 'rate', name='uq_deposit_params')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposits')
    # ### end Alembic commands ###
